### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by siim911** [hotio/bazarr#17]
am having below issue when i try manual download a Sub

Traceback (most recent call last):

  File "/app/bin/bazarr/get_subtitle.py", line 512, in manual_download_subtitle

    saved_subtitles = save_subtitles(video.original_path, [subtitle], single=single,

  File "/app/bin/bazarr/../libs/subliminal_patch/core.py", line 921, in save_subtitles

    with open(subtitle_path, \'wb\') as f:

PermissionError: [Errno 13] Permission denied: \'/data/media/Movies/The Great Alaskan Race (2019)/The Great Alaskan Race 2019 Bluray-1080p DTS [IT+EN] CYBER.ar.srt\

**Comment by mrhotio** [comment]
Fix your permissions.
